### ISSUE TITLE
Stacks get lost after re-setup of docker

### ISSUE THREAD

**Issue by HannesJo0139** [OpenMediaVault-Plugin-Developers/openmediavault-compose#1]
Today I had to uninstall and purge docker due to an issue of btrfs driver. After re-setup all the compose stacks were gone. The files still exist in the sharedfolder. But I assume I have to re-enter them manually? If so, for future versions it would be awesome to have some function that imports existing config files.

**Comment by ryecoaaron** [comment]
If you "apt-get remove openmediavault-compose" before purging docker, you wouldn't have lost the database entries and then the plugin could've just recreated all of the files.  I will look at importing all compose folders in the proper setup in a directory but it won't import just any compose file.

**Comment by HannesJo0139** [comment]
Ah that's nice to know if there is a next time. Yeah I think importing any compose file is unnecessary, but for instance lets say there is a directory swag/ with swag.yml and swag.env in it. So if it matches the plugin's pattern perfectly you could probably just import that stack?

**Comment by ryecoaaron** [comment]
yes but I was thinking it would import all of them instead of one at a time.  Which would be preferrable?

**Comment by HannesJo0139** [comment]
Yeah that would be great. So in my case after pointing to the correct sharedfolder, everything would have showed up at once.

**Comment by ryecoaaron** [comment]
6.3 is in the repo.  Tested importing 30 randomly generated with this script to generate:
