### ISSUE TITLE
Changes to /etc/docker/daemon.json are lost

### ISSUE THREAD

**Issue by subjut** [OpenMediaVault-Plugin-Developers/openmediavault-compose#10]
I have installed docker (through omv plugins) onto a zfs volume and need to run docker with the zfs driver enabled. To use it I have to add the option `"storage-driver": "zfs"` to `/etc/docker/daemon.json` ([docker documentation](https://docs.docker.com/storage/storagedriver/zfs-driver/)). I can do it manually, restart docker over ssh and it works, but I noticed that the option is lost at some point. When I then restart the server, docker starts with the overlay2 driver and most of my containers fail to start because of permission problems.

Is it possible to add additional options to `daemon.json`? If not, could we have a field, where we can add additional options, or a checkbox to indicate, that the file should not be touched by the plugin?

Thanks.

**Comment by ryecoaaron** [comment]
If you leave the Docker storage field on the Settings tab blank, it will not do anything with the daemon.json file.

**Comment by subjut** [comment]
Ah, good to know. Thanks.

Maybe this could be mentioned on the settings page.

**Comment by ryecoaaron** [comment]
Just added it. https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-compose/commit/099a103fa6849dbbd2db0750b00a07764e302313
