### ISSUE TITLE
Wrong path for compose files

### ISSUE THREAD

**Issue by jaype87** [OpenMediaVault-Plugin-Developers/openmediavault-compose#11]
I think the recent commit 4ea0d80bf2c5c02ae4e137e662d41f71b42c21db removed too many slashes in some cases.

It seems, that changes made to compose files are saved to 
<Share Name with removed trailing "/"><Stack Name> (which is wrong, as it creates a new folder for each Stack at the level of the share, not inside it)
but read from
<Share Name with trailing "/"><Stack Name> when "up"-ing the stack.

Therefore changes made to the compose files in the UI aren't applied.

**Comment by ryecoaaron** [comment]
Fixed in 6.9.4.  Every sharedfolder on my system had a trailing slash.  So, I didn't notice this.

**Comment by jaype87** [comment]
Thanks for the quick fix!
