### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Ikes72** [OpenMediaVault-Plugin-Developers/openmediavault-compose#13]
Hello

First of all, thanks for this excellent plugin.
Concerning the files tab, would it be possible to add a tag column, as exists elsewhere in OMV? Or alternatively a column with the file modification date?

Concerning the image tab, would it be possible to have a column with the used/unused status, like in Portainer?

Thanks !

Ikes

**Comment by ryecoaaron** [comment]
[Add file date column](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-compose/commit/61659ee255ec44d5715cb82c2201c6b6463dfb06)
[Turn description column into a tag view](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-compose/commit/45086c4679d77b060c5d737a4dd6a7f19c46f468)

**Comment by ryecoaaron** [comment]
How does portainer determine if the image is in use?  If it is referenced in a compose file or a container is actively using it?

**Comment by Ikes72** [comment]
I don't how Portainer do this exact exactly.
With `docker ps`, it's possible to list all images in used.

`docker ps -a --format="{{.Image}}"`

**Comment by ryecoaaron** [comment]
That would be if a container is using it.  That is easy to add.

**Comment by ryecoaaron** [comment]
6.9.7 in the repo with all of these changes.

**Comment by Ikes72** [comment]
Fast and effective. 

Thanks.

Ikes

**Comment by ryecoaaron** [comment]
I had to revert the change to tags in the Description column because some people were using hyperlinks.  In 6.9.8 in the repo now, I added a Tags column that is populated from the same description field.  It is hidden by default but this will allow users to pick the view they want.
