### ISSUE TITLE
Description as tag(s) on Files tab wery bad

### ISSUE THREAD

**Issue by alexshalex** [OpenMediaVault-Plugin-Developers/openmediavault-compose#14]
Please bring back the old description on Files tab. It's better to make a new tags column. In the old version of the description, it was possible to create a link url using html tags like <a href= . This made it possible to link to running services. And links to project pages on github and docker hub.Thank you.

**Comment by ryecoaaron** [comment]
I had no idea anyone did that.  I will revert the column.

**Comment by ryecoaaron** [comment]
6.9.8 is in the repo now.  The Description column is back to the way it was and a Tags column has been added (hidden by default) that is populated from the same description field.  This allows the user to pick the view they want.

**Comment by alexshalex** [comment]
Thank you very much for bringing back the old description! This field is really very convenient to use.
![1](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-compose/assets/39776817/3a8e1f5b-2015-44a1-9483-2b7a5d03f7d5)
![2](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-compose/assets/39776817/48ac631a-40fa-40bf-8fdf-73500ac95a03)

**Comment by ryecoaaron** [comment]
Do you add the container link because it isn't working on the Services tab?
