### ISSUE TITLE
Shared folders overview

### ISSUE THREAD

**Issue by ThirtySomething** [OpenMediaVault-Plugin-Developers/openmediavault-compose#15]
Shared folders used in the new docker compose plugin are not marked as referenced in the storage->shared folders->overview.

**Comment by ThirtySomething** [comment]
I'm sorry, this is the old repo.

**Comment by ryecoaaron** [comment]
This is the correct repo.  Looking into this.

**Comment by ryecoaaron** [comment]
I filed an issue for OMV itself to fix this - https://github.com/openmediavault/openmediavault/issues/1569

**Comment by ThirtySomething** [comment]
Thank you very much for supporting this issue.
