### ISSUE TITLE
Change to use `docker-compose-plugin` instead of  standalone `docker-compose` on newer docker versions

### ISSUE THREAD

**Issue by ksonney** [OpenMediaVault-Plugin-Developers/openmediavault-compose#16]
Debian Version 11.3 (bullseye)
OMV Version 6.5.3-1 (Shaitan)
OMV-Compose Version 6.9.9
Docker-ce Version 20.10.5+dfsg1, build 55c4c88
Processor BCM2835
Kernel Linux 6.1.21-v8+

As of July 2023, docker no longer ships a package for docker-compose (see https://docs.docker.com/compose/migrate/), and OMV-Compose will now install the (old, bad) version included with debian. In order for OMV-Compose to support the newer docker versions, the following need to be done :

1. Install `docker-compose-plugin` instead of `docker-compose`
2. Change the internal syntax to use `docker compose` instead of `docker-compose`

OR

1. Manually install the correct `docker-compose` binary from github for the correct arch as per https://docs.docker.com/compose/install/standalone/

**Comment by ryecoaaron** [comment]
The docker compose plugin has always been installed on non-i836 systems and is being used by symlinking to the compose plugin’s binary. But a few days ago, I switched to calling it thru docker.

https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-compose/commit/4696cb90bf483e84e49747a120b9005e35d68903
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-compose/blob/main/srv/salt/omv/deploy/compose/30docker.sls#L26

**Comment by ryecoaaron** [comment]
This will be fixed in omv 6.5.4.
