### ISSUE TITLE
Changing /etc/docker/daemon.json file

### ISSUE THREAD

**Issue by alexshalex** [OpenMediaVault-Plugin-Developers/openmediavault-compose#17]
I am trying to use IPv6 on openmediavault and in docker.
According to the recommendations from https://docs.docker.com/config/daemon/ipv6/
i make changes to /etc/docker/daemon.json
for example like this:
{
   "data-root": "/var/lib/docker",
   "experimental": true
   "ip6tables": true,
   "ipv6": true
   "fixed-cidr-v6": "fd00::/64"
}
After that I create a new Compose file in Files.
As soon as I click the Save button, the /etc/docker/daemon.json file changes to default
{
   "data-root": "/var/lib/docker"
}
That is, all my changes made to /etc/docker/daemon.json are lost.
openmediavault 6.7.0-1 (Shaitan)
openmediavault-compose 6.9.9

**Comment by ryecoaaron** [comment]
As the docker storage field on the Settings tab says, if you want to use a custom daemon.json config, leave that field blank. The plugin will not change the file at all then.
