### ISSUE TITLE
When a Dockerfile it's renamed the new one it's created but the old onew stills stored

### ISSUE THREAD

**Issue by qmarquez** [OpenMediaVault-Plugin-Developers/openmediavault-compose#22]
I notice when rename a Dockerfile the new one it's created but the old one stills stored in the disk. I guess that this behaviour, specially becuase I notices too share folders with the compose .yml files. I guess the file, if it's empty the folder too, should be deleted on file rename, or same that compose, the renaming should be blocked

**Comment by ryecoaaron** [comment]
I actually thought I had that blocked already but looking at the code, it isn't.  I will make the name read only when editing.  If someone wants to rename something, they can just create a new one and delete the old one.

**Comment by ryecoaaron** [comment]
Compose file renaming already was blocked.  Dockerfile renaming is now blocked.  That will go out in the next release.
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-compose/commit/173821743e251a4c9e50d3de7c90ebb5a79eab3f

**Comment by qmarquez** [comment]
Cool! thanks a lot @ryecoaaron
