### ISSUE TITLE
ArgumentCountError while trying to delete Dockerfiles

### ISSUE THREAD

**Issue by daimond113** [OpenMediaVault-Plugin-Developers/openmediavault-compose#23]
I encountered an issue while attempting to delete a Dockerfile in OpenMediaVault: "Invalid RPC response. Please check the syslog for more information.". The syslog reports the following error: "PHP Fatal error: Uncaught ArgumentCountError: 3 arguments are required, 2 given in /usr/share/openmediavault/engined/rpc/compose.inc:554". Here is the specific line of code in question: https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-compose/blob/720b70c1135a6699b787984fb5881d1821860ffc/usr/share/openmediavault/engined/rpc/compose.inc#L554

I would be grateful if I could get some explanation as to why it happens, or if this is a bug to get it fixed.

**Comment by ryecoaaron** [comment]
Fix in 7.0.6 in repo now.
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-compose/commit/5d79bcdfe671fd23ca6a9a44e6f57427bdfb6482
