### ISSUE TITLE
Sync compose file with database

### ISSUE THREAD

**Issue by glebaccon** [OpenMediaVault-Plugin-Developers/openmediavault-compose#24]
Hello,

First of all thanks you for the good work you do.

Is it possible to sync compose and env file with the database when file is saved from outside the plugin page ?

If not possible or not wanted, can you improve the UI of the edit page ? 

Firstly: I think  the compose textarea and the env textarea can be in a Tab widget (first tab for compose file and second tab for env file) with more height to edit the content without needing to scroll or manually resize the textarea.

Secondly: The save button is at the bottom of the page so we have to scroll down to save the changes. This seems to be the same with all edit pages in OMV, so it may not be your responsibility, right ?

**Comment by ryecoaaron** [comment]
> Is it possible to sync compose and env file with the database when file is saved from outside the plugin page ?

I will try to see if this is easy to do.

> Firstly: I think the compose textarea and the env textarea can be in a Tab widget (first tab for compose file and second tab for env file) with more height to edit the content without needing to scroll or manually resize the textarea.

I don't think there is a tab widget for a form page.  I could make the compose code editor taller but that would cause issues on lower resolution screens and potentially hide the environment variable editor making it not obvious that it exists.

> Secondly: The save button is at the bottom of the page so we have to scroll down to save the changes. This seems to be the same with all edit pages in OMV, so it may not be your responsibility, right ?

Correct, this is not the decision of the plugin and I cannot change this.

**Comment by glebaccon** [comment]
OK I undestand, the first point would already be very cool.

**Comment by ryecoaaron** [comment]
I have added the sync button but still need to do some more testing.
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-compose/commit/bd87c26f4c2f201c34d3c5d25db8aa2fb2dccc18

**Comment by glebaccon** [comment]
Woo looks very good, I can't wait to try it ;)

**Comment by ryecoaaron** [comment]
This is in the repo now.
