### ISSUE TITLE
feature: add up --remove-orphan option

### ISSUE THREAD

**Issue by sbe-arg** [OpenMediaVault-Plugin-Developers/openmediavault-compose#26]
somehow the ability to --remove-orphan during updates

is somewhat a pain to have to do down, edit file, then up to remove orphans

**Comment by ryecoaaron** [comment]
Added in commit https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-compose/commit/ae18c9f8c1886c60a3502354f50dc997279f01b2

Will probably be released in the next couple of days.
