### ISSUE TITLE
Feature Request: Cache lists of files, services, etc

### ISSUE THREAD

**Issue by HannesJo0139** [OpenMediaVault-Plugin-Developers/openmediavault-compose#29]
I really appreciate all the work you've put into the compose plugin. There is just one thing annoying me. Sometimes I'm switching quickly between view of files, services, etc. - and it always takes several seconds to reload all the information. 

So I was wondering if you would consider implementing a simple caching. So lets say I click on files and I was already there just some minutes before, you could just show the cached data from before until reloading is complete. That would highly improve usability in my eyes.

**Comment by ryecoaaron** [comment]
This has been added.  Still testing though.
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-compose/commit/9ce21c01f08b8cf4f262c2ffaa262adb443a4efd
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-compose/commit/050a916fc1c2f8d5198900f27e85bce4e68e30fe

**Comment by ryecoaaron** [comment]
7.2 is in the repo.

**Comment by HannesJo0139** [comment]
Nice, works like a charm. Thanks!
