### ISSUE TITLE
Possible issue with docker compose when upgrading a container

### ISSUE THREAD

**Issue by delaviux** [OpenMediaVault-Plugin-Developers/openmediavault-compose#33]
For some time now I've been noticing that when updating (pull) any container using the GUI, a text appears that seems to come from the internal operations that are executed when updating.
What I mean is that I get this:
```
export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; docker compose --file '/srv/dev-disk-by-uuid-5e449d86-ea83-4abb-a537-93a3ec29c6ce/docker_archivos/ddclient/ddclient.yml' --file "/srv/dev-disk-by-uuid-5e449d86-ea83-4abb-a537-93a3ec29c6ce/docker_archivos/ddclient/compose.override.yml" --env-file '/srv/dev-disk-by-uuid-5e449d86-ea83-4abb-a537-93a3ec29c6ce/docker_archivos/global.env' --env-file '/srv/dev-disk-by-uuid-5e449d86-ea83-4abb-a537-93a3ec29c6ce/docker_archivos/ddclient/ddclient.env' pull  2>&1

 ddclient Pulling 
 ddclient Pulled 

END OF LINE
```
When normally before I only got this:
```
 ddclient Pulling 
 ddclient Pulled 

END OF LINE
```
I don't know if this is a small bug or if it's done on purpose or if it only happens to me. But I found it curious and a little aesthetically unpleasant to see those lines of text every time I update any of my containers.

**Comment by ryecoaaron** [comment]
It was purposely done.  Myself and other users like to run some commands from the command line and this makes it easier.  I fail to see why it is unpleasant but I will see if I can make it optional.

https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-compose/commit/c61a9d33a7a5526fa4744bb16ee2025d23b6bdff#diff-f602c797ee685df8d7155499009df85ff742d70a45f2fc4da0def34a23315e71R813

**Comment by delaviux** [comment]
If it's done on purpose then it's fine. Don't pay too much attention to me. I'm one of those people who pay too much attention to details. And I was simply afraid that some commands were not being executed correctly when they suddenly appeared there. You can consider this issue closed.

**Comment by ryecoaaron** [comment]
This change will go out in the next release.  The default will be to not show the command since I would guess the majority of users don't need it.  There is a checkbox on the Setttings tab to show the command.
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-compose/commit/0240e73cf9798343404c1bccaef92c2396e1b339
