### ISSUE TITLE
Backup files fails for container with trailing "/" in volume path

### ISSUE THREAD

**Issue by dariusaurius** [OpenMediaVault-Plugin-Developers/openmediavault-compose#34]
Hi,

thanks for your nice plugin, I love it! I noticed that the file backup for a compose file is not processed when the volume path ends with a "/" for the container side.

This error is logged: 

`[composebackup] no docker compose config match found for /docker/data/vaultwarden/data:/data`

My volume configuration looked like this:

```
    volumes:
      - /docker/data/vaultwarden/data:/data/
```

After changing it to this, it copied the files to the backup location:

```
    volumes:
      - /docker/data/vaultwarden/data:/data
```

I confirmed it with other compose files.

Regards

**Comment by ryecoaaron** [comment]
Will be fixed in next release (sometime today)
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-compose/commit/72c3bd4df7cffd4b95bdab3ca015ba5e1ec1ba00

**Comment by dariusaurius** [comment]
Many thanks [ryecoaaron](https://github.com/ryecoaaron), tried different combinations with a slash on the end and had no issues in the last 8 weeks with it anymore. This was the fastest fix, which I witnesed on Github.
