### ISSUE TITLE
compose.override.yml is not removed when removing the file in webUI

### ISSUE THREAD

**Issue by Mat-DB** [OpenMediaVault-Plugin-Developers/openmediavault-compose#37]
Since the new file (```compose.override.yml```) is added the directory of a service is not deleted when removing the "file" in the omv webUI.
The 2 other files (```service.yml``` and  ```service.env```) are deleted but this one stays and therefor also the directory.

Is it possible to also delete the ```compose.override.yml``` file (and the whole directory) when removing a file in the webUI?

Thanks!

Side question, is it allowed to remove the undeleted file and directory? Or will this cause trouble with omv or the plugin?

**Comment by ryecoaaron** [comment]
I had the code setting override file name but never ran the unlink.  Fixed - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-compose/commit/f25dc990a446c38f8280b039e54c8b9b89bb13ba

The directory is deleted when empty - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-compose/blob/main/usr/share/openmediavault/engined/rpc/compose.inc#L704

Yes, you can remove the override file and directory.

I will push the change later.

**Comment by ryecoaaron** [comment]
7.2.16 in the repo now.
