### ISSUE TITLE
Feature Request: Add a button to restart the compose file

### ISSUE THREAD

**Issue by TheRedCyclops** [OpenMediaVault-Plugin-Developers/openmediavault-compose#39]
I often find myself testing something on a compose file and each time I want to restart I have to stop the compose file, wait, and start it again. I think a button that just restarted the file (preferably with docker compose down && docker compose up -d, docker compose restart in my experience doesn't properly reload the file) would be a great improvement to user experience.

**Comment by ryecoaaron** [comment]
I don't understand when this is needed.  If you change the compose file, you just click the Up button and it will restart the container(s) if the compose file changed.  If you just want to restart the container, there is a restart button on the Services tab.

**Comment by TheRedCyclops** [comment]
I didn't realize that function was available, thanks!
