### ISSUE TITLE
Enhancement: inspect container 

### ISSUE THREAD

**Issue by dsm1212** [OpenMediaVault-Plugin-Developers/openmediavault-compose#4]
I was thinking I didn't need the network tab in portainer, but I already ran into a use case. The current UI does not show the IP address for a container. I think I could live without the full network listing support. Maybe add an inspect button on the container list? That should solve all container detail requests. IE. "docker inspect -container name-" output.

**Comment by ryecoaaron** [comment]
The Containers tab already has an Inspect button.

**Comment by dsm1212** [comment]
I must be blind. I see four buttons. Pull, up, restart and logs. Where?

**Comment by ryecoaaron** [comment]
Sorry, it is on the Stats tab since it is a docker command not a docker-compose command.
![image](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-compose/assets/1914475/f94f1f1b-9b3b-4261-a66f-5fee280ddb81)

**Comment by dsm1212** [comment]
Nice, thanks! I will. Closethis.
