### ISSUE TITLE
Docker-compose shared folders issue

### ISSUE THREAD

**Issue by Patrik-Tkacik** [OpenMediaVault-Plugin-Developers/openmediavault-compose#41]
I have an issue with the compose settings, when I change the folders, namely compose and data, it needs to apply the changes but when I do I get an error:

![image](https://github.com/user-attachments/assets/42d7b62f-30ce-4cce-92c0-e89cd0f6d573)

omv-salt deploy run --no-color compose 2>&1

ubuntu22:

----------

ID: configure_etc_docker_dir

Function: [file.directory](http://file.directory/)

Name: /etc/docker

Result: True

Comment: The directory /etc/docker is in the correct state

Started: 19:11:33.832389

Duration: 2.45 ms

Changes:

----------

ID: /etc/docker/daemon.json

Function: file.serialize

Result: True

Comment: File /etc/docker/daemon.json is in the correct state

Started: 19:11:33.835005

Duration: 58.769 ms

Changes:

----------

ID: docker_install_packages

Function: pkg.installed

Result: True

Comment: All specified packages are already installed and are at the desired version

Started: 19:11:35.065892

Duration: 67.303 ms

Changes:

----------

ID: docker_compose_install_packages

Function: pkg.installed

Result: True

Comment: All specified packages are already installed and are at the desired version

Started: 19:11:35.133409

Duration: 96.194 ms

Changes:

----------

ID: docker_purged_packages

Function: pkg.purged

Result: True

Comment: None of the targeted packages are installed or partially installed

Started: 19:11:35.229791

Duration: 1.143 ms

Changes:

----------

ID: docker

Function: service.running

Result: True

Comment: The service docker is already running

Started: 19:11:35.232894

Duration: 95.984 ms

Changes:

----------

ID: /etc/systemd/system/docker.service.d/waitAllMounts.conf

Function: file.managed

Result: True

Comment: File /etc/systemd/system/docker.service.d/waitAllMounts.conf is in the correct state

Started: 19:11:35.329236

Duration: 86.359 ms

Changes:

----------

ID: systemd_daemon_reload_docker

Function: [cmd.run](http://cmd.run/)

Name: systemctl daemon-reload

Result: True

Comment: State was not run because none of the onchanges reqs changed

Started: 19:11:35.417273

Duration: 0.013 ms

Changes:

----------

ID: create_usr_local_bin_dir

Function: [file.directory](http://file.directory/)

Name: /usr/local/bin

Result: True

Comment: The directory /usr/local/bin is in the correct state

Started: 19:11:35.417408

Duration: 1.371 ms

Changes:

----------

ID: configure_compose_scheduled_backup

Function: file.managed

Name: /etc/cron.d/omv-compose-backup

Result: True

Comment: File /etc/cron.d/omv-compose-backup is in the correct state

Started: 19:11:35.418911

Duration: 127.256 ms

Changes:

----------

ID: configure_compose_scheduled_update

Function: file.managed

Name: /etc/cron.d/omv-compose-update

Result: True

Comment: File /etc/cron.d/omv-compose-update is in the correct state

Started: 19:11:35.546363

Duration: 127.23 ms

Changes:

----------

ID: configure_compose_scheduled_prune

Function: file.managed

Name: /etc/cron.d/omv-compose-prune

Result: True

Comment: File /etc/cron.d/omv-compose-prune is in the correct state

Started: 19:11:35.673791

Duration: 126.212 ms

Changes:

----------

ID: configure_compose_global_env_file

Function: file.managed

Name: docker-compose/global.env

Result: False

Comment: Specified file docker-compose/global.env is not an absolute path

Started: 19:11:35.800203

Duration: 1.446 ms

Changes:

Summary for ubuntu22

-------------

Succeeded: 12

Failed: 1

-------------

Total states run: 13

Total run time: 791.730 ms

[ERROR ] Specified file docker-compose/global.env is not an absolute path

now the thing is that the path is elsewhere, here:
/srv/dev-disk-by-uuid-a7c7e191-5c2e-49b4-9f26-606380641ac2/docker-compose/config.env

Edit: found out data folder is fine, but the compose section is throwing the error...

**Comment by ryecoaaron** [comment]
On the Shared Folder tab (not in the compose plugin), what is the absolute path of the docker-compose shared folder?

**Comment by Patrik-Tkacik** [comment]
@ryecoaaron the shared folders absolute path that I am setting for compose is 

/dev/disk/by-uuid/a7c7e191-5c2e-49b4-9f26-606380641ac2

if I copy it from the shared folders section in the web interface

**Comment by ryecoaaron** [comment]
I can't explain why saltstack is failing to resolve the absolute path of the shared folder using the OMV sharedfolder function - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-compose/blob/main/srv/salt/omv/deploy/compose/10compose.sls#L20

If this code was broken, it would be broken for everyone.  What type of filesystem is the shared folder on?  Can you try creating a new shared folder and use that in the plugin as a test?

**Comment by Patrik-Tkacik** [comment]
@ryecoaaron lol I cant even create a shared folder, I def broke something. Honestly after installing omv I couldnt get to download compose docker into it. Let me do a fresh install and try again, might take a while because it mapped the drives for like 2-3 hours

**Comment by Patrik-Tkacik** [comment]
They only provide an openmediavault v6, could that cause issues?

**Comment by ryecoaaron** [comment]
Who only provides OMV 6?  OMV 6 is EOL.

**Comment by ryecoaaron** [comment]
You can install Armbian and follow the guide - https://wiki.omv-extras.org/doku.php?id=omv7:armbian_bookworm_install
