### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by Jormono1** [OpenMediaVault-Plugin-Developers/openmediavault-compose#5]
I've been having this problem since yesterday,
In that time, here are things I have tried to remedy the problem:
 * I wiped and reinstalled the OS on the SSD (was a fresh install yesterday before this anyway)
 * I removed everything that wasn't media or personal files from the HDDs
 * I posted to the OMV forum and some users helped with troubleshooting [there](https://forum.openmediavault.org/index.php?thread/48077-can-t-seem-to-get-docker-setup-correctly/&pageNo=1)
 * I received an update to the OMV compose plugin, this did not effect the issue
 *  This is the current error message [error 6-4-23-11AM.txt](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-compose/files/11646069/error.6-4-23-11AM.txt)

**Comment by ryecoaaron** [comment]
This isn’t a bug in the plugin.  While saltstack is failing because your network is blocking github, the install is fine. I cant make the autocompose functionality dynamic based on your network allowing github access. importing examples also allows github access. Since omv-extras repos on github, you really should allow
github access.

**Comment by Jormono1** [comment]
I just checked my router settings, I don't have anything setup to deny access to anything. And a lot of the installation process has pulled from github, I don't understand how that could be possible but is there any way I could test that?

**Comment by ryecoaaron** [comment]
try:

wget https://github.com/OpenMediaVault-Plugin-Developers/installScript/raw/master/install

**Comment by Jormono1** [comment]
`root@openmediavault:~# wget https://github.com/OpenMediaVault-Plugin-Developers/                                                                                                                                                             installScript/raw/master/install
--2023-06-04 14:35:14--  https://github.com/OpenMediaVault-Plugin-Developers/ins                                                                                                                                                             tallScript/raw/master/install
Resolving github.com (github.com)... 140.82.112.3
Connecting to github.com (github.com)|140.82.112.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/OpenMediaVault-Plugin-Developers/installScript/master/install [following]
--2023-06-04 14:37:30--  https://raw.githubusercontent.com/OpenMediaVault-Plugin-Developers/installScript/master/install
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20407 (20K) [text/plain]
Saving to: ‘install’

install                                                     100%[========================================================================================================================================>]  19.93K  --.-KB/s    in 0.001s

2023-06-04 14:37:30 (18.2 MB/s) - ‘install’ saved [20407/20407]
`

**Comment by ryecoaaron** [comment]
Ok, how about:

wget https://github.com/Red5d/docker-autocompose/raw/master/autocompose.py
wget https://raw.githubusercontent.com/Red5d/docker-autocompose/master/autocompose.py

**Comment by Jormono1** [comment]
This is the new output
[wget output2.txt](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-compose/files/11646457/wget.output2.txt)

**Comment by ryecoaaron** [comment]
It sure seems like one of your python libs is not right then.  I don't know what the problem is.

**Comment by ryecoaaron** [comment]
Try:

sudo rm -rfv /var/cache/salt/minion/extrn_files/base/github.com
sudo omv-salt deploy run compose

**Comment by Jormono1** [comment]
that errored out, see attached
[wget output3.txt](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-compose/files/11646548/wget.output3.txt)

**Comment by ryecoaaron** [comment]
weird.  One more thing to try:

sudo /usr/bin/salt-call --local saltutil.clear_cache
sudo omv-salt stage run prepare
sudo omv-salt deploy run compose

**Comment by ryecoaaron** [comment]
Are you using a proxy?  Your 599 error means this:

599 Network Connect Timeout Error
HTTP response status code 599 Network Connect Timeout Error is an unofficial HTTP status code used by some proxies to indicate that there has been a [HTTP Connection](https://http.dev/http-connection) timeout behind the proxy to a HTTP client in front of the proxy.

**Comment by Jormono1** [comment]
Errored on the last command again. And no proxy. I'm not sure I even know what that is. 
[wget output4.txt](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-compose/files/11646577/wget.output4.txt)

**Comment by ryecoaaron** [comment]
I don't know what else to say.  I hate to change code because one system is having a weird network issue.  I will have to think about it.

**Comment by Jormono1** [comment]
do you think its an issue with my local network? I had some DNS issues when I setup home assistant (I have no idea what I did to fix it, it sort of just started working at some point, most of the changes were on the server side but I did change the DNS server settings on my router). I seem to remember that particular issue being a "not uncommon" problem, there were guides to resolving it and everything.

**Comment by ryecoaaron** [comment]
Hard to say but it doesn't seem like since wget works.

**Comment by Jormono1** [comment]
could maybe my ISP be doing something along the lines of a proxy server and I just dont know about it? I just did some googling on the subject and I've certainly not setup something like that but I'm on a small locally operated fiber network.

**Comment by ryecoaaron** [comment]
Possibly but I would think it would cause the same issues for wget.  I don't know what the saltsack file.managed code is doing.  I found [this issue](https://github.com/saltstack/salt/issues/40607) on the saltstack github issues.  I suggests removing a bit more than I had you do but I didn't want to suggest that because I don't know what it could do.  If you want to try the following, I would curious if it works but it might cause major issues.

sudo rm -rf /var/cache/salt/minion
sudo /usr/bin/salt-call --local saltutil.clear_cache
sudo omv-salt stage run prepare
sudo omv-salt deploy run compose

Otherwise, I might just include the autocompose file with the plugin and remove the download altogether.  There aren't many updates anyway.

**Comment by Jormono1** [comment]
Doesn't appear to have done any damage, looks just like the last one.
[wget output5.txt](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-compose/files/11646810/wget.output5.txt)

**Comment by ryecoaaron** [comment]
6.7.11 is in the repo.  It doesn't download autocompose anymore.

**Comment by Jormono1** [comment]
That appears to have worked, thanks so much!
