### ISSUE TITLE
Possibility to update image of Dockerfile

### ISSUE THREAD

**Issue by rabesocke** [OpenMediaVault-Plugin-Developers/openmediavault-compose#6]
There seems to be no possibility to update an image, that is used in a Dockerfile.

For example: I have a Dockerfile for Nextcloud (as described in the Nextcloud repo) to use cron, imagick etc. In Portainer, I went to the image overview and pulled this image in a new version. After that I created a new image with the Dockerfile.

**Comment by rabesocke** [comment]
That's what I'm doing. Nextcloud suggest to build an own image if you need special extensions like Samba, Imagick, etc.

This is the beginning of the Dockerfile. With that, I create an own image based on the existing Nextcloud image. The Nextcloud image is updated and I want to update my custom image. But it seems, that the `Build` button doesn't update the Nextcloud image.

```
FROM nextcloud:26

RUN set -ex; \
    \
    apt-get update; \
    apt-get install -y --no-install-recommends \
#        ffmpeg \
        ghostscript \
        libmagickcore-6.q16-6-extra \
        procps \
        smbclient \
        supervisor \
#       libreoffice \
    ; \

(...) 
```

**Comment by ryecoaaron** [comment]
The plugin is just running docker build.  Normally you would do a docker pull nextcloud:26 before the build.  You could create a very simple nextcloud:26 docker-compose on the Files tab and click Pull there when you needed an updated image or I guess I could add a button that would pull the image in the Dockerfile.

**Comment by rabesocke** [comment]
👍  for a pull button at Dockerfile

I think, this would me the most straight forward way instead of adding an useless compose file only to pull newer images.

**Comment by ryecoaaron** [comment]
6.7.17 in the repo.  It adds a button to pull and build the dockerfile by adding the --pull flag to the docker build command
