### ISSUE TITLE
loose file permissions on created files and folders in the compose plugins 'shared-folder'

### ISSUE THREAD

**Issue by d1vzero** [OpenMediaVault-Plugin-Developers/openmediavault-compose#9]
Hi,
I wonder if there is a good reasons, why the user and file-access permissions on the created docker files and folders in the openmediavault-compose shared folder are very loose?
Wouldn't it be better to narrow down the permissions as much as possible since the docker yaml files might also contain somehow important data that should not be accessible by every user (group is users) . Even "others" do have read-access to the files.
However, changes made in the permissions will be overwritten during next deployment of a changed docker configuration (i.e. added container) .

Is it possible to tighten file permissions by editing 
/srv/salt/omv/deploy/compose/10compose.sls and
/srv/salt/omv/deploy/compose/20dockerfile.sls
or will this change break things?

Thank you

**Comment by ryecoaaron** [comment]
That is a good point.  There is no reason to have open permissions.  I will test a change that will use the permissions of the shared folder.  Then the user can determine permissions when they are creating the shared folder.

**Comment by ryecoaaron** [comment]
6.9.1 in the repo.  You can set the user, group and permissions of the directories/files on the Settings tab.  It will default to root:root and 700 for dirs / 600 for files.

**Comment by d1vzero** [comment]
Perfect. Thank you!
